# Generated by Django 2.2.7 on 2019-12-03 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_user', models.CharField(max_length=200, null=True)),
                ('expense', models.BigIntegerField(default=0)),
                ('expense_date', models.DateTimeField(verbose_name='date published')),
                ('expense_detail', models.CharField(max_length=200)),
            ],
        ),
    ]
