# Generated by Django 2.2.7 on 2020-01-13 07:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kakeibo', '0002_expense_expense_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='expense_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
