# Generated by Django 2.2.7 on 2020-01-13 09:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kakeibo', '0004_auto_20200113_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='expense_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
